/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lt' at '12/8/15 4:18 PM' with Gradle 2.9
 *
 * @author lt, @date 12/8/15 4:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
