SET SCHEMA APP;
DROP TABLE User;
DROP TABLE Account;

CREATE TABLE User (
    UserID INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY,
    Username VARCHAR(128) UNIQUE NOT NULL,
	CONSTRAINT USERNAME_CONSTRAINT 
    CHECK (LENGTH(Username) >= 2),
	Password VARCHAR(128) NOT NULL
    CreationDate DATE NOT NULL 
);

CREATE TABLE Pattern (
    PatternID INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY,
    Name VARCHAR(40) NOT NULL, 
	Description CLOB NOT NULL 
);

CREATE TABLE PatternPart (
    PartID INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY,
    PatternID INT NOT NULL 
    REFERENCES Pattern(PatternID),
    Name VARCHAR(20) NOT NULL,
	Description CLOB NOT NULL 
);
